name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ contains(steps.changed-files.outputs.modified_files, 'Nancy/Nancy/Nancy.proj') }}

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v20

  build:
    runs-on: ubuntu-latest

    needs: check
    if: ${{ needs.check.outputs.status == 'true' }}

    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.sln"

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: Nancy/global.json

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        run: dotnet test $SOLUTION /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
