name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Nancy/Nancy.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: Nancy/global.json
        
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test $SOLUTION /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal